GLOBAL:
  DOMAIN: hackerone.com

# ASSET DISCOVERY GLOBAL VARIABLES
ASSET_DISCOVERY:
  UTILITIES_FOLDER_PATH: "/root/WebArmor/asset_discovery/UTILS_FOLDER"
  OUTPUT_FOLDER_PATH: "/root/WebArmor/DATA_FOLDER/asset_discovery"
  DOMAIN_INFO_FILE_PATH: "/root/WebArmor/DATA_FOLDER/asset_discovery/domain_info.txt"
  NUCLEI_TKO_TEMPLATE: "/root/WebArmor/asset_discovery/utils/detect-all-takeovers.yaml"
  BRUTEFORCE_WORDLIST: "/root/WebArmor/asset_discovery/utils/wordlist.txt"
  RESOLVERS: "/root/WebArmor/asset_discovery/utils/resolvers.txt"
  SUBDOMAINS_FILE_PATH: "/root/WebArmor/DATA_FOLDER/asset_discovery/all-unique-subdomains.txt"
  PROBED_SUBDOMAINS_FILE_PATH: "/root/WebArmor/DATA_FOLDER/asset_discovery/probed_subs.txt"
  TECHNOLOGIES_FILE_PATH: "/root/WebArmor/DATA_FOLDER/asset_discovery/technologies.txt"
  SHODAN_FILE_PATH: "/root/WebArmor/DATA_FOLDER/asset_discovery/shodan.txt"
  SHODAN_API_KEY: 
  CHAOS_KEY: ODIyfiJtQVxpnoLcUeV60YXxMX7qeXJJxHdQqjtQxkBUQ0q1zAC2oEe35i3N1hTx

# CRAWL GLOBAL VARIABLES
CRAWLING_URL_ENUMERATION:
  OUTPUT_FOLDER_PATH: "/root/WebArmor/DATA_FOLDER/crawling_url_enumeration"

# OWASP GLOBAL VARIABLES 
OWASP:
  OP_OUTPUT_PATH: "/root/WebArmor/DATA_FOLDER/owasp_scanning/open_redirect.txt"
  XSS_OUTPUT_PATH: "/root/WebArmor/DATA_FOLDER/owasp_scanning/xss.txt"
  SQLI_OUTPUT_PATH: "/root/WebArmor/DATA_FOLDER/owasp_scanning/sqli_output/"
  XXE_OUTPUT_PATH: "/root/WebArmor/DATA_FOLDER/owasp_scanning/xxe.txt"
  XXE_TEMPS_PATH: "/root/WebArmor/owasp_scanning/utils/xxe-templates/"



#NETWORK GLOBAL VARIABLES
NETWORK_SCAN:
  SCAN_RESULT_PATH: "/root/WebArmor/DATA_FOLDER/network_scanning/network_scan.txt"



#REPORT GLOBAL VARIABLES
REPORT:
  MAIN_PAGE_PATH: "/root/WebArmor/Report.html"
  OWASP_PAGE_PATH: "/root/WebArmor/DATA_FOLDER/reporting/owasp.html"
  NETWORK_PAGE_PATH: "/root/WebArmor/DATA_FOLDER/reporting/network.html"
  VULNSCAN_PAGE_PATH: "/root/WebArmor/DATA_FOLDER/reporting/vulnscan.html"
  URLS_PAGE_PATH: "/root/WebArmor/DATA_FOLDER/reporting/urls.html"
  INFO_TEMP_PATH: "/root/WebArmor/reporting/utils/info_temp.txt"
  NETWORK_TEMP_PATH: "/root/WebArmor/reporting/utils/network_temp.txt"
  OWASP_TEMP_PATH: "/root/WebArmor/reporting/utils/owasp_temp.txt"
  URLS_TEMP_PATH: "/root/WebArmor/reporting/utils/urls_temp.txt"
  VULNSCAN_TEMP_PATH: "/root/WebArmor/reporting/utils/vulnscan_temp.txt"
  GITHUB_GIST_TOKEN:
  
  

